<?php

namespace Database\Seeders;

use App\Models\Producto;
use Illuminate\Database\Seeder;

class ProductoSeeder extends Seeder
{
    public function run(): void
    {
        $productos = [

            // ── Licores (categoria_id = 1) ───────────────────
            [
                'cod_producto'     => 'LIC-001',
                'nombre'           => 'Ron Cartavio Blanco',
                'categoria_id'     => 1,
                'marca'            => 'Cartavio',
                'unidad_medida'    => 'und',
                'contenido'        => '750ml',
                'precio_compra'    => 20.00,
                'precio_minorista' => 28.00,
                'precio_mayorista' => 25.00,
                'stock_minimo'     => 5,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'LIC-002',
                'nombre'           => 'Whisky Johnnie Walker Red',
                'categoria_id'     => 1,
                'marca'            => 'Johnnie Walker',
                'unidad_medida'    => 'und',
                'contenido'        => '750ml',
                'precio_compra'    => 55.00,
                'precio_minorista' => 70.00,
                'precio_mayorista' => 65.00,
                'stock_minimo'     => 3,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'LIC-003',
                'nombre'           => 'Vodka Absolut Original',
                'categoria_id'     => 1,
                'marca'            => 'Absolut',
                'unidad_medida'    => 'und',
                'contenido'        => '750ml',
                'precio_compra'    => 40.00,
                'precio_minorista' => 55.00,
                'precio_mayorista' => 50.00,
                'stock_minimo'     => 3,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'LIC-004',
                'nombre'           => 'Ron Bacardí Blanco',
                'categoria_id'     => 1,
                'marca'            => 'Bacardí',
                'unidad_medida'    => 'und',
                'contenido'        => '750ml',
                'precio_compra'    => 25.00,
                'precio_minorista' => 35.00,
                'precio_mayorista' => 30.00,
                'stock_minimo'     => 5,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'LIC-005',
                'nombre'           => 'Pisco Queirolo',
                'categoria_id'     => 1,
                'marca'            => 'Queirolo',
                'unidad_medida'    => 'und',
                'contenido'        => '750ml',
                'precio_compra'    => 15.00,
                'precio_minorista' => 22.00,
                'precio_mayorista' => 20.00,
                'stock_minimo'     => 5,
                'activo'           => true,
            ],

            // ── Gaseosas (categoria_id = 2) ──────────────────
            [
                'cod_producto'     => 'GAS-001',
                'nombre'           => 'Inca Kola',
                'categoria_id'     => 2,
                'marca'            => 'Inca Kola',
                'unidad_medida'    => 'bot',
                'contenido'        => '1.5L',
                'precio_compra'    => 2.50,
                'precio_minorista' => 4.00,
                'precio_mayorista' => 3.50,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'GAS-002',
                'nombre'           => 'Coca Cola',
                'categoria_id'     => 2,
                'marca'            => 'Coca Cola',
                'unidad_medida'    => 'bot',
                'contenido'        => '1.5L',
                'precio_compra'    => 2.50,
                'precio_minorista' => 4.00,
                'precio_mayorista' => 3.50,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'GAS-003',
                'nombre'           => 'Sprite',
                'categoria_id'     => 2,
                'marca'            => 'Sprite',
                'unidad_medida'    => 'bot',
                'contenido'        => '1.5L',
                'precio_compra'    => 2.00,
                'precio_minorista' => 3.50,
                'precio_mayorista' => 3.00,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'GAS-004',
                'nombre'           => 'Fanta Naranja',
                'categoria_id'     => 2,
                'marca'            => 'Fanta',
                'unidad_medida'    => 'bot',
                'contenido'        => '1.5L',
                'precio_compra'    => 2.00,
                'precio_minorista' => 3.50,
                'precio_mayorista' => 3.00,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'GAS-005',
                'nombre'           => 'Pepsi',
                'categoria_id'     => 2,
                'marca'            => 'Pepsi',
                'unidad_medida'    => 'bot',
                'contenido'        => '1.5L',
                'precio_compra'    => 2.50,
                'precio_minorista' => 4.00,
                'precio_mayorista' => 3.50,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],

            // ── Snacks (categoria_id = 3) ─────────────────────
            [
                'cod_producto'     => 'SNA-001',
                'nombre'           => "Papas Lay's Original",
                'categoria_id'     => 3,
                'marca'            => "Lay's",
                'unidad_medida'    => 'und',
                'contenido'        => '42g',
                'precio_compra'    => 1.50,
                'precio_minorista' => 2.50,
                'precio_mayorista' => 2.00,
                'stock_minimo'     => 12,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'SNA-002',
                'nombre'           => 'Doritos Nacho Cheese',
                'categoria_id'     => 3,
                'marca'            => 'Doritos',
                'unidad_medida'    => 'und',
                'contenido'        => '42g',
                'precio_compra'    => 1.50,
                'precio_minorista' => 2.50,
                'precio_mayorista' => 2.00,
                'stock_minimo'     => 12,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'SNA-003',
                'nombre'           => 'Chizitos',
                'categoria_id'     => 3,
                'marca'            => 'Evercrisp',
                'unidad_medida'    => 'und',
                'contenido'        => '42g',
                'precio_compra'    => 1.20,
                'precio_minorista' => 2.00,
                'precio_mayorista' => 1.80,
                'stock_minimo'     => 12,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'SNA-004',
                'nombre'           => 'Cuates',
                'categoria_id'     => 3,
                'marca'            => 'Frito-Lay',
                'unidad_medida'    => 'und',
                'contenido'        => '42g',
                'precio_compra'    => 1.20,
                'precio_minorista' => 2.00,
                'precio_mayorista' => 1.80,
                'stock_minimo'     => 12,
                'activo'           => true,
            ],

            // ── Galletas (categoria_id = 4) ───────────────────
            [
                'cod_producto'     => 'GAL-001',
                'nombre'           => 'Oreo',
                'categoria_id'     => 4,
                'marca'            => 'Oreo',
                'unidad_medida'    => 'paq',
                'contenido'        => '144g',
                'precio_compra'    => 2.00,
                'precio_minorista' => 3.50,
                'precio_mayorista' => 3.00,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'GAL-002',
                'nombre'           => 'Galleta Vainilla',
                'categoria_id'     => 4,
                'marca'            => 'Casino',
                'unidad_medida'    => 'paq',
                'contenido'        => '160g',
                'precio_compra'    => 1.50,
                'precio_minorista' => 2.50,
                'precio_mayorista' => 2.20,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'GAL-003',
                'nombre'           => 'Soda Victoria',
                'categoria_id'     => 4,
                'marca'            => 'Victoria',
                'unidad_medida'    => 'paq',
                'contenido'        => '190g',
                'precio_compra'    => 1.20,
                'precio_minorista' => 2.00,
                'precio_mayorista' => 1.80,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],

            // ── Hielo (categoria_id = 5) ──────────────────────
            [
                'cod_producto'     => 'HIE-001',
                'nombre'           => 'Hielo en bolsa 3kg',
                'categoria_id'     => 5,
                'marca'            => null,
                'unidad_medida'    => 'bol',
                'contenido'        => '3kg',
                'precio_compra'    => 3.00,
                'precio_minorista' => 5.00,
                'precio_mayorista' => 4.50,
                'stock_minimo'     => 8,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'HIE-002',
                'nombre'           => 'Hielo en bolsa 5kg',
                'categoria_id'     => 5,
                'marca'            => null,
                'unidad_medida'    => 'bol',
                'contenido'        => '5kg',
                'precio_compra'    => 4.50,
                'precio_minorista' => 7.00,
                'precio_mayorista' => 6.50,
                'stock_minimo'     => 8,
                'activo'           => true,
            ],

            // ── Cigarrillos (categoria_id = 6) ────────────────
            [
                'cod_producto'     => 'CIG-001',
                'nombre'           => 'Marlboro Red',
                'categoria_id'     => 6,
                'marca'            => 'Marlboro',
                'unidad_medida'    => 'und',
                'contenido'        => '20 cigarros',
                'precio_compra'    => 8.00,
                'precio_minorista' => 12.00,
                'precio_mayorista' => 11.00,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'CIG-002',
                'nombre'           => 'Lucky Strike Azul',
                'categoria_id'     => 6,
                'marca'            => 'Lucky Strike',
                'unidad_medida'    => 'und',
                'contenido'        => '20 cigarros',
                'precio_compra'    => 7.50,
                'precio_minorista' => 11.50,
                'precio_mayorista' => 10.50,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'CIG-003',
                'nombre'           => 'Hamilton Azul',
                'categoria_id'     => 6,
                'marca'            => 'Hamilton',
                'unidad_medida'    => 'und',
                'contenido'        => '20 cigarros',
                'precio_compra'    => 5.00,
                'precio_minorista' => 8.00,
                'precio_mayorista' => 7.00,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],

            // ── Otros (categoria_id = 7) ──────────────────────
            [
                'cod_producto'     => 'OTR-001',
                'nombre'           => 'Agua San Luis',
                'categoria_id'     => 7,
                'marca'            => 'San Luis',
                'unidad_medida'    => 'bot',
                'contenido'        => '625ml',
                'precio_compra'    => 0.60,
                'precio_minorista' => 1.20,
                'precio_mayorista' => 1.00,
                'stock_minimo'     => 15,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'OTR-002',
                'nombre'           => 'Red Bull',
                'categoria_id'     => 7,
                'marca'            => 'Red Bull',
                'unidad_medida'    => 'und',
                'contenido'        => '250ml',
                'precio_compra'    => 4.00,
                'precio_minorista' => 7.00,
                'precio_mayorista' => 6.50,
                'stock_minimo'     => 8,
                'activo'           => true,
            ],
            [
                'cod_producto'     => 'OTR-003',
                'nombre'           => 'Jugo Frugos Durazno',
                'categoria_id'     => 7,
                'marca'            => 'Frugos',
                'unidad_medida'    => 'bot',
                'contenido'        => '500ml',
                'precio_compra'    => 1.20,
                'precio_minorista' => 2.00,
                'precio_mayorista' => 1.80,
                'stock_minimo'     => 10,
                'activo'           => true,
            ],
        ];

        foreach ($productos as $data) {
            Producto::create($data);
        }
    }
}
